/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Landing_Page_jFrame_Manager.java
 *
 * Created on Nov 6, 2012, 2:16:46 AM
 */

package bankingsystem;



/**
 *
 * @author Arron
 */
public class Landing_Page_jFrame_Manager extends javax.swing.JFrame {

          
	
    //-------------------------------------------------------------
    //          Constructor
    //-------------------------------------------------------------
    /** Creates new form Landing_Page_jFrame_Manager */
    public Landing_Page_jFrame_Manager() {
        initComponents();
        setLocationRelativeTo(null);
        this.setExtendedState(this.MAXIMIZED_BOTH);


    }
    
    //-------------------------------------------------------------
    //          Methods
    //-------------------------------------------------------------

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        btnTransfer = new javax.swing.JButton();
        welcome = new javax.swing.JLabel();
        btnLookupAccount = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        createAcct = new javax.swing.JButton();
        btnCloseAccount = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        btnChangeRate = new javax.swing.JButton();
        btnWithdraw = new javax.swing.JButton();
        btnSendBill = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        btnCloseCreditCard = new javax.swing.JButton();
        message2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnLookupUser = new javax.swing.JButton();
        btnDeleteUser = new javax.swing.JButton();
        btnUpdateUserInformation = new javax.swing.JButton();
        btnAddUser = new javax.swing.JButton();
        accountNum = new javax.swing.JFormattedTextField();
        btnOpenCD = new javax.swing.JButton();
        btnCloseCD = new javax.swing.JButton();
        btnRollOverCD = new javax.swing.JButton();
        op = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        accountType = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        balance = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        ssn = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        accountNumber = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        lname = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        fname = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuOpen = new javax.swing.JMenu();
        menuLogin = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        menuExit = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnTransfer.setText("Transfer");
        btnTransfer.setMaximumSize(new java.awt.Dimension(150, 50));
        btnTransfer.setMinimumSize(new java.awt.Dimension(150, 50));
        btnTransfer.setPreferredSize(new java.awt.Dimension(150, 50));
        btnTransfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransferActionPerformed(evt);
            }
        });

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, welcome, org.jdesktop.beansbinding.ELProperty.create("${name}"), welcome, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        btnLookupAccount.setText("Look up Account");
        btnLookupAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLookupAccountActionPerformed(evt);
            }
        });

        jButton9.setText("Deposit");
        jButton9.setMaximumSize(new java.awt.Dimension(150, 50));
        jButton9.setMinimumSize(new java.awt.Dimension(150, 50));
        jButton9.setPreferredSize(new java.awt.Dimension(150, 50));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        createAcct.setText("Create Account");
        createAcct.setMaximumSize(new java.awt.Dimension(150, 50));
        createAcct.setMinimumSize(new java.awt.Dimension(150, 50));
        createAcct.setPreferredSize(new java.awt.Dimension(150, 50));
        createAcct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAcctActionPerformed(evt);
            }
        });

        btnCloseAccount.setText("Close Account");
        btnCloseAccount.setMaximumSize(new java.awt.Dimension(150, 50));
        btnCloseAccount.setMinimumSize(new java.awt.Dimension(150, 50));
        btnCloseAccount.setPreferredSize(new java.awt.Dimension(150, 50));
        btnCloseAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseAccountActionPerformed(evt);
            }
        });

        jButton12.setText("Issue ATM Card");
        jButton12.setMaximumSize(new java.awt.Dimension(150, 50));
        jButton12.setMinimumSize(new java.awt.Dimension(150, 50));
        jButton12.setPreferredSize(new java.awt.Dimension(150, 50));
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        btnChangeRate.setText("Change Interest Rate");
        btnChangeRate.setMaximumSize(new java.awt.Dimension(150, 50));
        btnChangeRate.setMinimumSize(new java.awt.Dimension(150, 50));
        btnChangeRate.setPreferredSize(new java.awt.Dimension(150, 50));
        btnChangeRate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeRateActionPerformed(evt);
            }
        });

        btnWithdraw.setText("Withdraw");
        btnWithdraw.setMaximumSize(new java.awt.Dimension(150, 50));
        btnWithdraw.setMinimumSize(new java.awt.Dimension(150, 50));
        btnWithdraw.setPreferredSize(new java.awt.Dimension(150, 50));
        btnWithdraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWithdrawActionPerformed(evt);
            }
        });

        btnSendBill.setText("Send Bill");
        btnSendBill.setMaximumSize(new java.awt.Dimension(150, 50));
        btnSendBill.setMinimumSize(new java.awt.Dimension(150, 50));
        btnSendBill.setPreferredSize(new java.awt.Dimension(150, 50));
        btnSendBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendBillActionPerformed(evt);
            }
        });

        jButton16.setText("Modify Transaction");
        jButton16.setMaximumSize(new java.awt.Dimension(150, 50));
        jButton16.setMinimumSize(new java.awt.Dimension(150, 50));
        jButton16.setPreferredSize(new java.awt.Dimension(150, 50));
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        btnCloseCreditCard.setText("Close Credit Card");
        btnCloseCreditCard.setMaximumSize(new java.awt.Dimension(150, 50));
        btnCloseCreditCard.setMinimumSize(new java.awt.Dimension(150, 50));
        btnCloseCreditCard.setPreferredSize(new java.awt.Dimension(150, 50));
        btnCloseCreditCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseCreditCardActionPerformed(evt);
            }
        });

        message2.setText("Enter account number to search");

        jButton1.setText("Adjust All Rate");
        jButton1.setMaximumSize(new java.awt.Dimension(150, 50));
        jButton1.setMinimumSize(new java.awt.Dimension(150, 50));
        jButton1.setPreferredSize(new java.awt.Dimension(150, 50));

        btnLookupUser.setText("Look up user");
        btnLookupUser.setMaximumSize(new java.awt.Dimension(150, 50));
        btnLookupUser.setMinimumSize(new java.awt.Dimension(150, 50));
        btnLookupUser.setPreferredSize(new java.awt.Dimension(150, 50));
        btnLookupUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLookupUserActionPerformed(evt);
            }
        });

        btnDeleteUser.setText("Delete User");
        btnDeleteUser.setMaximumSize(new java.awt.Dimension(150, 50));
        btnDeleteUser.setMinimumSize(new java.awt.Dimension(150, 50));
        btnDeleteUser.setPreferredSize(new java.awt.Dimension(150, 50));
        btnDeleteUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteUserActionPerformed(evt);
            }
        });

        btnUpdateUserInformation.setText("Update User Information");
        btnUpdateUserInformation.setMaximumSize(new java.awt.Dimension(150, 50));
        btnUpdateUserInformation.setMinimumSize(new java.awt.Dimension(150, 50));
        btnUpdateUserInformation.setPreferredSize(new java.awt.Dimension(150, 50));
        btnUpdateUserInformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateUserInformationActionPerformed(evt);
            }
        });

        btnAddUser.setText("Create User");
        btnAddUser.setMaximumSize(new java.awt.Dimension(150, 50));
        btnAddUser.setMinimumSize(new java.awt.Dimension(150, 50));
        btnAddUser.setPreferredSize(new java.awt.Dimension(150, 50));
        btnAddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddUserActionPerformed(evt);
            }
        });

        accountNum.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("############"))));
        accountNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountNumActionPerformed(evt);
            }
        });

        btnOpenCD.setText("Open CD");
        btnOpenCD.setMaximumSize(new java.awt.Dimension(150, 50));
        btnOpenCD.setMinimumSize(new java.awt.Dimension(150, 50));
        btnOpenCD.setPreferredSize(new java.awt.Dimension(150, 50));
        btnOpenCD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenCDActionPerformed(evt);
            }
        });

        btnCloseCD.setText("Close CD");
        btnCloseCD.setMaximumSize(new java.awt.Dimension(150, 50));
        btnCloseCD.setMinimumSize(new java.awt.Dimension(150, 50));
        btnCloseCD.setPreferredSize(new java.awt.Dimension(150, 50));
        btnCloseCD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseCDActionPerformed(evt);
            }
        });

        btnRollOverCD.setText("Roll Over CD");
        btnRollOverCD.setMaximumSize(new java.awt.Dimension(150, 50));
        btnRollOverCD.setMinimumSize(new java.awt.Dimension(150, 50));
        btnRollOverCD.setPreferredSize(new java.awt.Dimension(150, 50));
        btnRollOverCD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRollOverCDActionPerformed(evt);
            }
        });

        jTextField7.setText("Account Type");

        jTextField5.setText("Balance");

        jTextField3.setText("SSN");

        jTextField1.setText("Account Number");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField12.setText("First Name");

        jTextField14.setText("Last Name");
        jTextField14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField14ActionPerformed(evt);
            }
        });

        jTextField16.setText("Overdraft Protection");

        jMenu1.setText("File");

        menuOpen.setText("Open");

        menuLogin.setText("Login");
        menuLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLoginActionPerformed(evt);
            }
        });
        menuOpen.add(menuLogin);

        jMenu1.add(menuOpen);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu4.setText("Help");
        jMenuBar1.add(jMenu4);

        jMenu5.setText("Exit");

        menuExit.setText("Exit");
        menuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuExitActionPerformed(evt);
            }
        });
        jMenu5.add(menuExit);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(229, 229, 229)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(accountNum, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnLookupAccount)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(welcome, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(message2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(createAcct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnTransfer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnOpenCD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(btnCloseCD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btnRollOverCD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(btnCloseCreditCard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnWithdraw, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnDeleteUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(btnSendBill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btnCloseAccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnChangeRate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnAddUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnUpdateUserInformation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnLookupUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(accountNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(ssn, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(balance, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(accountType, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(op, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lname, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(fname, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(203, 203, 203))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(welcome, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnLookupAccount)
                        .addComponent(accountNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(message2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(createAcct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnCloseAccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnAddUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnWithdraw, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDeleteUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnChangeRate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnLookupUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnTransfer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnUpdateUserInformation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnCloseCreditCard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSendBill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnOpenCD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCloseCD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRollOverCD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(accountNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ssn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(balance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(accountType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(op, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(108, Short.MAX_VALUE))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTransferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransferActionPerformed
        transfer_JDialog transfer = new transfer_JDialog(this,true);
        transfer.run();
    }//GEN-LAST:event_btnTransferActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        Deposit_JDialog deposit = new Deposit_JDialog(this,true);
        deposit.run();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void createAcctActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAcctActionPerformed
        Create_Account_Page_JDialog create = new Create_Account_Page_JDialog(this,true);
        create.run();
    }//GEN-LAST:event_createAcctActionPerformed

    private void btnCloseAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseAccountActionPerformed
        Close_Accout_page_JDialog close = new Close_Accout_page_JDialog(this,true);
        close.run();
    }//GEN-LAST:event_btnCloseAccountActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void btnChangeRateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeRateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnChangeRateActionPerformed

    private void btnWithdrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWithdrawActionPerformed
        Withdraw_JDialog wd = new Withdraw_JDialog(this,true);
        wd.run();
    }//GEN-LAST:event_btnWithdrawActionPerformed

    private void btnSendBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendBillActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSendBillActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton16ActionPerformed

    private void btnCloseCreditCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseCreditCardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCloseCreditCardActionPerformed

    private void btnLookupUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLookupUserActionPerformed
        Find_User_JDialog find = new Find_User_JDialog(this,true);
        find.run();
    }//GEN-LAST:event_btnLookupUserActionPerformed

    private void menuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuExitActionPerformed

    private void menuLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLoginActionPerformed
        Login_Jframe_Form login = new Login_Jframe_Form();
        login.run();
    }//GEN-LAST:event_menuLoginActionPerformed

    private void btnDeleteUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteUserActionPerformed
            Delete_User_JDialog del = new Delete_User_JDialog(this,true);
            del.run();
           
    }//GEN-LAST:event_btnDeleteUserActionPerformed

    private void btnAddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddUserActionPerformed
        Create_User_jFrame_Form adduser = new Create_User_jFrame_Form(this,true);
        adduser.run();
    }//GEN-LAST:event_btnAddUserActionPerformed

    private void btnOpenCDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenCDActionPerformed
        OpenCD_JFrame cd = new OpenCD_JFrame(this,true);
        cd.run();
    }//GEN-LAST:event_btnOpenCDActionPerformed

    private void btnCloseCDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseCDActionPerformed
        Closing_CD close = new Closing_CD(this, true);
        close.run();
    }//GEN-LAST:event_btnCloseCDActionPerformed

    private void btnRollOverCDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRollOverCDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRollOverCDActionPerformed

    private void btnUpdateUserInformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateUserInformationActionPerformed
        Update_User_jFrame_Form up = new Update_User_jFrame_Form(this, true);
        up.run();
    }//GEN-LAST:event_btnUpdateUserInformationActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField14ActionPerformed

    private void accountNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountNumActionPerformed
        this.btnLookupAccountActionPerformed(evt);
    }//GEN-LAST:event_accountNumActionPerformed

    private void btnLookupAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLookupAccountActionPerformed
        UserParser up = new UserParser("");
        AccountParser ap = new AccountParser("");
        
        //input information requested from xml
        int acctNum = Integer.parseInt(accountNum.getText());//from lookup field input
        int ssn1 = ap.getAccount(acctNum).getCustomerID();//get CustomerID from Account Object, -1 = no account
        
        //Search in user.xml for ssn,-1 = not match in user.xml

        if(up.getIndexFromSSN(ssn1)==-1){
            System.out.println("SSN did found match in user.xml");
        }else{System.out.println("SSN found match in user.xml, SSN = " + ssn1 + " at index = " + up.getIndexFromSSN(ssn1));}


        System.out.println("ssn1 = " + ssn1);//no this SSN found in user.xml
        if(ssn1==-1){
            //
            message2.setText("No Customer Found in Accounts.xml, CustomerID = " + ssn1);
            fname.setText("");
            lname.setText("");
            balance.setText("");
            accountNumber.setText("");
            ssn.setText("");
            accountType.setText("");
        }else{
            message2.setText("Found in Accounts.xml, but not in user.xml");
            double balance1 = ap.getAccount(acctNum).checkBalance();
            String balance2 = String.valueOf(balance1);//convert int to string
            String acctNum1 = String.valueOf(acctNum);//convert int to string
            int acctType = ap.getAccount(acctNum).getAccountType();
            
            String acctType1;//convert int to string
            /*
            * <li>1=SimpleSavings</li>
            * <li>2=CDs</li>
            * <li>3=TMB</li>
            * <li>4=G/D</li>
            * <li>5=LLoans</li>
            * <li>6=SLoans</li>
            * <li>7=CreditCards</li>
            * */
            switch(acctType){
                case 1: acctType1 = "SimpleSaving";
                    break;
                case 2: acctType1 = "CD";
                    break;
                case 3: acctType1 = "TMB";
                    break;
                case 4: acctType1 = "G/D";
                    break;
                case 5: acctType1 = "LLoans";
                    break;
                case 6: acctType1 = "SLoans";
                    break;
                case 7: acctType1 = "CreditCards";
                    break;
                default: acctType1 = "Unknown Type,in default. Check for acctType error";
            }
            
            String ssn2 = String.valueOf(ssn1);

            //out put account information
            balance.setText(balance2);
                accountNumber.setText(acctNum1);
                ssn.setText(ssn2);
                accountType.setText(acctType1);
            //further check in user.xml
            if(up.getIndexFromSSN(ssn1)>-1){
                message2.setText("Found in Accounts.xml, and user.xml. CustomerID(ssn) = " + ssn1);
                
                String fname1 = up.getFName(up.getIndexFromSSN(ssn1));//if ssn1=-1,this will be outofbound
                String lname1 = up.getLName(up.getIndexFromSSN(ssn1));//if ssn1=-1,this will be outofbound

                //output informations when found match in user.xml
                fname.setText(fname1);
                lname.setText(lname1);
            }//end user.xml part
        }
        
    }//GEN-LAST:event_btnLookupAccountActionPerformed

    /**
    * @param args the command line arguments
    */
    public void run() {
                new Landing_Page_jFrame_Manager().setVisible(true);
            }
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Landing_Page_jFrame_Manager().setVisible(true);
            }
        });
    }//end main args

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField accountNum;
    private javax.swing.JTextField accountNumber;
    private javax.swing.JTextField accountType;
    private javax.swing.JTextField balance;
    private javax.swing.JButton btnAddUser;
    private javax.swing.JButton btnChangeRate;
    private javax.swing.JButton btnCloseAccount;
    private javax.swing.JButton btnCloseCD;
    private javax.swing.JButton btnCloseCreditCard;
    private javax.swing.JButton btnDeleteUser;
    private javax.swing.JButton btnLookupAccount;
    private javax.swing.JButton btnLookupUser;
    private javax.swing.JButton btnOpenCD;
    private javax.swing.JButton btnRollOverCD;
    private javax.swing.JButton btnSendBill;
    private javax.swing.JButton btnTransfer;
    private javax.swing.JButton btnUpdateUserInformation;
    private javax.swing.JButton btnWithdraw;
    private javax.swing.JButton createAcct;
    private javax.swing.JTextField fname;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField lname;
    private javax.swing.JMenu menuExit;
    private javax.swing.JMenuItem menuLogin;
    private javax.swing.JMenu menuOpen;
    private javax.swing.JLabel message2;
    private javax.swing.JTextField op;
    private javax.swing.JTextField ssn;
    private javax.swing.JLabel welcome;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

}
