/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Create_Account_jFrame_Form.java
 *
 * Created on Nov 6, 2012, 2:22:27 AM
 */
package bankingsystem;

/**
 *
 * @author Arron
 * @since Nov 6, 2012, 2:22:27 AM
 * @version 1
 */
public class Send_Bill extends javax.swing.JDialog {

    // End of variables declaration
    //-------------------------------------------------------------
    //          Constructor
    //-------------------------------------------------------------
    /**
     * Creates new form Create_Account_jFrame_Form
     */
    public Send_Bill(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        ap = new AccountParser("");
        initComponents();
        setLocationRelativeTo(null);//sets the jFram_Form in the center
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        acctnum = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        message = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnSend = new javax.swing.JButton();
        btnCCSend = new javax.swing.JButton();
        btnLoanSend = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        acctnum.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("############"))));

        jLabel9.setText("Send All bills of Loans");

        message.setText("Result:");

        jLabel8.setText("Account Number");

        jLabel3.setText("Send All bills of CreditCards");

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Apple Braille", 1, 14)); // NOI18N
        jLabel2.setText("Send Bill Control Panel.");

        btnSend.setText("Send");
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });

        btnCCSend.setText("Send");
        btnCCSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCCSendActionPerformed(evt);
            }
        });

        btnLoanSend.setText("Send");
        btnLoanSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoanSendActionPerformed(evt);
            }
        });

        jLabel1.setText("(Only CreditCard and Loans Account)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 184, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(message, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnCancel)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel1))
                                        .addGap(18, 18, 18)
                                        .addComponent(acctnum, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnCCSend, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnLoanSend, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnSend))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(acctnum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSend))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCCSend)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnLoanSend))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(message, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCancel)
                .addGap(56, 56, 56))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
        int emptycount = 0;
        if (acctnum.getText().isEmpty()) {
            message.setText("account number field empty");
            emptycount++;
            return;
        }
        if (emptycount == 0) {
            int accountnum = Integer.parseInt(acctnum.getText());
            String bill;
        
            switch (ap.getAccountTypeByAccountNumber(accountnum)) {
                case -1:
                    message.setText("Incorrect account number, no account found");
                    break;
                case 5:
                    message.setText("This is a Long Term Loan.");
                    LoanAccounts lloan = ap.getLoanAccount(accountnum);
                    bill = lloan.SendoutBills();
                    message.setText(bill);
                    ap.WriteFile();
                case 6:
                    message.setText("This is a Short term loan.");
                    LoanAccounts sloan = ap.getLoanAccount(accountnum);
                    bill = sloan.SendoutBills();
                    message.setText(bill);
                    ap.WriteFile();
                    break;
                case 7:
                    message.setText("This is a Credit Card.");
                    CreditCards cc = ap.getCreditCardAccount(accountnum);
                    bill = cc.SendoutBills();
                    message.setText(bill);
                    ap.WriteFile();
                    break;
                case 1:
                    message.setText("Saving,no bill");
                    break;
                case 2:
                    message.setText("CD,no bill");
                    break;
                case 3:
                    message.setText("TMB,no bill");
                    break;
                case 4:
                    message.setText("G/D,no bill");
                    break;
                default:
                    message.setText("Check fields.");
            }
        }
    }//GEN-LAST:event_btnSendActionPerformed

    private void btnLoanSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoanSendActionPerformed
        message.setText(ap.SendOutAllLoanBills());
    }//GEN-LAST:event_btnLoanSendActionPerformed

    private void btnCCSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCCSendActionPerformed
        message.setText(ap.SendOutAllCreditCardBills());
    }//GEN-LAST:event_btnCCSendActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                Send_Bill dialog = new Send_Bill(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }//end main args

    public void run() {
        Send_Bill dialog = new Send_Bill(new javax.swing.JFrame(), true);
        dialog.addWindowListener(new java.awt.event.WindowAdapter() {

            public void windowClosing(java.awt.event.WindowEvent e) {
                System.exit(0);
            }
        });
        dialog.setVisible(true);
    }
    private AccountParser ap;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField acctnum;
    private javax.swing.JButton btnCCSend;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnLoanSend;
    private javax.swing.JButton btnSend;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel message;
    // End of variables declaration//GEN-END:variables
}
