package bankingsystem;

/**
 *
 * @author Arron
 */
public class transfer_JDialog extends javax.swing.JDialog {

    /**
     * Creates new form transfer_JDialog
     */
    public transfer_JDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fromAccount = new javax.swing.JTextField();
        amount = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        toAccount = new javax.swing.JTextField();
        message = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("From Account");

        jLabel2.setText("Amount");

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        jLabel3.setText("To Account");

        message.setText("Result:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(fromAccount, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                                    .addComponent(amount, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(toAccount)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(106, 106, 106)
                                .addComponent(btnSubmit)
                                .addGap(38, 38, 38)
                                .addComponent(btnCancel)))
                        .addGap(0, 116, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(message, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(fromAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(toAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(amount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(message, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSubmit)
                    .addComponent(btnCancel))
                .addGap(53, 53, 53))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        
        int facct = Integer.parseInt(this.fromAccount.getText());
        int tacct = Integer.parseInt(this.toAccount.getText());
        double amt = Double.parseDouble(this.amount.getText());
        
        AccountParser ap = new AccountParser("");
        
        int acctType = ap.getAccount(facct).getAccountType();//acctType for source account
        int acctType2 = ap.getAccount(tacct).getAccountType();//acctType for target account
        
        int a=0,b=0;
        //check if valid transfer accounts
        //---------------------------------------------------------------------
        if((acctType!=1)&&(acctType!=3)&&(acctType!=4)){
            message.setText("transfer from account not a valid account");
            a++;
        }
        if((acctType2!=1)&&(acctType2!=3)&&(acctType2!=4)){
            message.setText("transfer from account not a valid account");
            a++;
        }
        //---------------------------------------------------------------------
        if((a+b)==0){
            int check=-1;
            String successMsg="";
        
            if(acctType == 1){
                double check2=ap.getSavingsAccount(facct).Transfer(amt);
                if(check2==amt){
                    successMsg="amount of "+check2+" transfered from Savings ";
                    check=1;
                }else{
                    message.setText("Not enough funds in transfer account");
                    return;
                }
            }
            if(acctType == 3){
                double check2=ap.getCheckingAccount(facct).Transfer(amt+1.25);
                if(check2==amt){
                    successMsg="amount of "+check2+" transfered from Checking ";
                    check=1;
                }else{
                    message.setText("Not enough funds in transfer account");
                    return;
                }
            }
            if(acctType == 4){
                double check2=ap.getCheckingAccount(facct).Transfer(amt);
                if(check2==amt){
                    successMsg="amount of "+check2+" transfered from Checking ";
                    check=1;
                }else{
                    message.setText("Not enough funds in transfer account");
                    return;
                }
            }
            
            if(check>-1){
                if(acctType2 == 1){
                    ap.getSavingsAccount(tacct).deposit(amt);
                    successMsg=successMsg+" into Savings";
                }
                if(acctType2 == 3){ap.getCheckingAccount(tacct).Deposit(amt);
                    successMsg=successMsg+" into Checking";
                }
                if(acctType2 == 4){ap.getCheckingAccount(tacct).Deposit(amt);
                    successMsg=successMsg+" into Checking";
                }
                message.setText(successMsg);
                ap.WriteFile();
                return;
            }else{
                message.setText("Unseccessful transfer");
            }
            
        }
        
    }//GEN-LAST:event_btnSubmitActionPerformed


            public void run() {
                transfer_JDialog dialog = new transfer_JDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amount;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JTextField fromAccount;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel message;
    private javax.swing.JTextField toAccount;
    // End of variables declaration//GEN-END:variables
}
