package bankingsystem;

/**
 *
 * @author Arron
 */
public class Withdraw_JDialog extends javax.swing.JDialog {

    /**
     * Creates new form Withdraw_JDialog
     */
    public Withdraw_JDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        acctNum = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        amt = new javax.swing.JTextField();
        btnWithdraw = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        message = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("From Account");

        jLabel2.setText("Amount");

        amt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amtActionPerformed(evt);
            }
        });

        btnWithdraw.setText("Submit");
        btnWithdraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWithdrawActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        message.setText("Result:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(btnWithdraw)
                        .addGap(38, 38, 38)
                        .addComponent(btnCancel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(message, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(acctNum, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(amt, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(126, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(acctNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(amt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(message, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnWithdraw)
                    .addComponent(btnCancel))
                .addGap(53, 53, 53))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnWithdrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWithdrawActionPerformed

        int account = Integer.parseInt(acctNum.getText());
        double amount = Double.parseDouble(amt.getText());

        AccountParser ap = new AccountParser("");

        int type = ap.getAccountTypeByAccountNumber(account);

        Checking chk;
        SavingsAccount sav;

        if (type == -1) {
            message.setText("account does not exist");
        } else {
            message.setText("Account found");
            int msg=0;
            switch(type){
                case 1:
                    sav =ap.getSavingsAccount(account);
                    System.out.println("Right account");
                    System.out.println(sav.checkBalance());
                    message.setText("Account Balance: " + sav.Withdrawl(amount));
                    System.out.println(sav.checkBalance());
                    ap.WriteFile();
                    break;
                case 3:
                    chk = ap.getCheckingAccount(account);
                    System.out.println("Right account");
                    System.out.println(chk.checkBalance());
                    msg=chk.Withdrawl(amount,ap);
                        if(msg==0){
                            message.setText("Account withdrawn successfuly." );
                        }else if(msg==1){
                            message.setText("Account overdrafted, but protected by savings" );
                        }else{
                            message.setText("Account overdrafted." );
                        }
                    System.out.println(chk.checkBalance());
                    ap.WriteFile();
                    break;
                case 4:
                     chk= ap.getCheckingAccount(account);
                    System.out.println("Right account");
                    System.out.println(chk.checkBalance());
                    msg=chk.Withdrawl(amount,ap);
                        if(msg==0){
                            message.setText("Account withdrawn successfuly." );
                        }else if(msg==1){
                            message.setText("Account overdrafted, but protected by savings" );
                        }else{
                            message.setText("Account overdrafted." );
                        }
                    System.out.println(chk.checkBalance());
                    ap.WriteFile();
                    break;
                default: message.setText("incorrect account type");
            }
        }
    }//GEN-LAST:event_btnWithdrawActionPerformed

    private void amtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amtActionPerformed
        this.btnWithdrawActionPerformed(evt);
    }//GEN-LAST:event_amtActionPerformed

    public void run() {
        Withdraw_JDialog dialog = new Withdraw_JDialog(new javax.swing.JFrame(), true);
        dialog.addWindowListener(new java.awt.event.WindowAdapter() {

            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                System.exit(0);
            }
        });
        dialog.setVisible(true);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField acctNum;
    private javax.swing.JTextField amt;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnWithdraw;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel message;
    // End of variables declaration//GEN-END:variables
}
